# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NetworkingCore' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NetworkingCore
  pod 'Alamofire'
  target 'NetworkingCoreTests' do
    # Pods for testing
  end

end
